version: 0.2

env:
    variables:
        CACHE_CONTROL: "86400"
        S3_BUCKET: "{{s3_bucket_url}}"
        BUILD_FOLDER: "dist"
        BUILD_ENV: "prod"
phases:
  install:
    runtime-versions:
        nodejs: 14
    commands:
        - echo NPM dependencies...
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started 
        - ng build --${BUILD_ENV}
  post_build:
     commands:
      - aws s3 cp dist s3://${S3_BUCKET}
      - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes